### ISSUE TITLE
Java error [jSSC-2.8_x86_64.dll+0xb5db]

### ISSUE THREAD

**Issue by j-augustyn** [UsbCANConverter-UCCbasic/uCCBViewer#2]
Hi, i can't run UCCB because it crashes. I tried install different java versions x64. x84 etc. Do you have any idea how to run this ? 
Thx.
[hs_err_pid2832.log](https://github.com/UsbCANConverter-UCCbasic/uCCBViewer/files/6107706/hs_err_pid2832.log)

**Comment by Lukasz-Juranek** [comment]
It crashes when You click connect ? It seems that there is issue with
serial port library. For me it works with:

jdk1.8.0_151\bin>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Could You test with this version ?

wt., 9 mar 2021 o 11:13 j-augustyn <notifications@github.com> napisał(a):

**Comment by j-augustyn** [comment]
Hes it crashes when i click connect. I installed Java(TM) SE Runtime Environment (build 1.8.0_151-b12) and it is working now. When i  update Java it stops working. Is it any workaround to have updated Java ?

**Comment by Lukasz-Juranek** [comment]
Please check this release

https://github.com/UsbCANConverter-UCCbasic/uCCBViewer/releases/tag/2.6

wt., 9 mar 2021 o 14:40 Łukasz Juranek ***@***.***>
napisał(a):

**Comment by j-augustyn** [comment]
Now it is working with latest Java :) Thank You very much !
I have additional question. Did you think about addidng color marking to new bytes?
![image](https://user-images.githubusercontent.com/16244497/110596093-2b2aff80-817f-11eb-862c-f8731c771dd9.png)

**Comment by Lukasz-Juranek** [comment]
this i good idea to add colors i will close this issue and try to add new feture for next release stay tuned.
